name: Mac (Installer)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bx-sh/setup-bx@master
      - run: "bash --version | head -1"
        shell: bash
      - run: echo "::add-path::packages/bin"
        shell: bash
      - run: rm assert.sh
        shell: bash
      - run: rm refute.sh
        shell: bash
      - run: "curl -o- https://assert.sh/installer.sh | bash"
        shell: bash
      - run: bx spec
        shell: bash
        env:
          VERBOSE: true
