name: BASH 4.3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: bx-sh/setup-bx@master
      - run: "bash --version | head -1"
        shell: bash
      - run: echo "::add-path::packages/bin"
        shell: bash
      - run: bx spec
        shell: bash
        env:
          VERBOSE: true
